title: HausaLearn Blog
email: shamsiyyasafiyan@gmail.com
description: >- 
  A space for sharing teaching reflections and special classroom moments.
baseurl: "" 
url: "https://hausalearn.github.io"
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html
